name: pr-assistant

on: workflow_dispatch
#   pull_request:
#   issue_comment:
jobs:
  pr_assistant_job:
    runs-on: ubuntu-latest
    name: Run pr assistant on every pull request, respond to user comments
    steps:
      - name: PR Assistant action step
        id: prassistant
        uses: khulnasoft/pr-assistant@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
